### ISSUE TITLE
How to cite the package?

### ISSUE THREAD

**Issue by fredust** [saeyslab/muscatWrapper#1]
Hello, thank you again for designing so many great packages. 
I used the muscatWrapper package in my analysis. How could I cite this package?  Should cite the muscat paper and also this github page? 

Thank you very much.

**Comment by browaeysrobin** [comment]
Hi @fredust 

Sorry for the late reply. You should indeed cite the Muscat paper by Crowell et al. It would also be nice if you could add the link to this wrapper.

Thanks!
